### ISSUE TITLE
Integrate docker-compose files

### ISSUE THREAD

**Issue by swsachith** [Data-to-Insight-Center/cyberinfrastructure-knowledge-network#2]
Currently, we have separate Docker files for starting Neo4j, Kafka, and Streamlit applications individually. To streamline, we need to create a unified Docker setup that allows us to start all these services simultaneously with a single command.

Order of Dependency:
1. neo4j
2. kafka
3. ckn-analytics-dashboard

Approach: Docker Compose Top-Level File
```
version: '3.8'

services:
  zookeeper:
    extends:
      file: kafka/docker-compose.yml
      service: zookeeper
  broker:
    extends:
      file: kafka/docker-compose.yml
      service: broker
  kafka-connect:
    extends:
      file: kafka/docker-compose.yml
      service: kafka-connect
  oracle-alert-processor:
    extends:
      file: kafka/docker-compose.yml
      service: oracle-alert-processor
  oracle-aggr-processor:
    extends:
      file: kafka/docker-compose.yml
      service: oracle-aggr-processor
  neo4j:
    extends:
      file: neo4j/docker-compose.yml
      service: neo4j
  ckn-dashboard:
    extends:
      file: dashboard/docker-compose.yml
      service: ckn-dashboard
```

Other Options
- Copy contents from 3 files into a new file: Redundancy
- Command like `docker-compose -f base-compose.yml -f kafka-compose.yml -f neo4j-compose.yml -f dashboard-compose.yml up`: Difficult to follow
